name: Publish Markdown Files
env:
  BLOG_REPO: dsvill06/blog
  PUBLISH_DIR: publish
on:
  workflow_dispatch:
  push:
    branches: [main]
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Obsidian Repo
        uses: actions/checkout@v3
        with:
          path: temp_md
      
      - name: Checkout Next.js Blog Repo
        uses: actions/checkout@v3
        with:
          path: temp_blog
          repository: "dsvill06/blog"
          token: ${{secrets.PAT_TOKEN}}
      
      - name: Install obsidian-export
        run: |
          wget https://github.com/zoni/obsidian-export/releases/download/v22.11.0/obsidian-export_Linux-x86_64.bin
          chmod +x obsidian-export_Linux-x86_64.bin
      
      - name: Process and Copy Files
        run: |
          # Export Obsidian files to temporary location
          ./obsidian-export_Linux-x86_64.bin ./temp_md temp_processed
          
          # Ensure target directory exists
          mkdir -p temp_blog/data/blog
          
          # Copy processed files to Next.js repo
          cp -r temp_processed/* temp_blog/data/blog/
          
          cd temp_blog
          
          # Configure Git
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
          
          # Commit and push changes
          git add .
          git commit -m "Update blog content from Obsidian vault"
          git push origin main
